[32mINFO[0m:     [03-05-2024 09:06:41] Set chroma_server_nofile to 65535
[32mINFO[0m:     [03-05-2024 09:09:53] Set chroma_server_nofile to 65535
[32mINFO[0m:     [03-05-2024 09:12:27] Set chroma_server_nofile to 65535
[32mINFO[0m:     [03-05-2024 09:13:21] Set chroma_server_nofile to 65535
[32mINFO[0m:     [03-05-2024 09:13:21] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [03-05-2024 09:13:21] Starting component System
[36mDEBUG[0m:    [03-05-2024 09:13:21] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [03-05-2024 09:13:21] Starting component SqliteDB
[36mDEBUG[0m:    [03-05-2024 09:13:21] Starting component QuotaEnforcer
[36mDEBUG[0m:    [03-05-2024 09:13:21] Starting component Posthog
[36mDEBUG[0m:    [03-05-2024 09:13:21] Starting component LocalSegmentManager
[36mDEBUG[0m:    [03-05-2024 09:13:21] Starting component SegmentAPI
[32mINFO[0m:     [03-05-2024 09:13:21] Started server process [[36m51239[0m]
[32mINFO[0m:     [03-05-2024 09:13:21] Waiting for application startup.
[32mINFO[0m:     [03-05-2024 09:13:21] Application startup complete.
[32mINFO[0m:     [03-05-2024 09:13:21] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [03-05-2024 09:13:39] ::1:56582 - "GET / HTTP/1.1" 404
[32mINFO[0m:     [03-05-2024 09:13:41] ::1:56601 - "GET / HTTP/1.1" 404
[32mINFO[0m:     [03-05-2024 09:13:55] ::1:56657 - "GET /api/docs HTTP/1.1" 404
[32mINFO[0m:     [03-05-2024 09:17:09] ::1:57536 - "GET /api/docs HTTP/1.1" 404
[32mINFO[0m:     [03-05-2024 15:00:47] ::1:59509 - "GET /docs HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:00:48] ::1:59509 - "GET /openapi.json HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:01:08] ::1:59608 - "GET /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[31mERROR[0m:    [03-05-2024 15:03:05] Input is a zero-length, empty document: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/Users/codietamida/anaconda3/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 852, in get
    await to_thread.run_sync(
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 831, in process_get
    get = GetEmbedding.model_validate(orjson.loads(raw_body))
orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)
[32mINFO[0m:     [03-05-2024 15:03:05] ::1:60094 - "POST /api/v1/collections/c5b7828b-bb37-4826-9b5a-d99f13f9939b/get HTTP/1.1" 500
[31mERROR[0m:    [03-05-2024 15:04:00] Input is a zero-length, empty document: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/Users/codietamida/anaconda3/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 961, in get_nearest_neighbors
    await to_thread.run_sync(
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 940, in process_query
    query = QueryEmbedding.model_validate(orjson.loads(raw_body))
orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)
[32mINFO[0m:     [03-05-2024 15:04:00] ::1:60323 - "POST /api/v1/collections/c5b7828b-bb37-4826-9b5a-d99f13f9939b/query HTTP/1.1" 500
[31mERROR[0m:    [03-05-2024 15:04:03] Input is a zero-length, empty document: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/Users/codietamida/anaconda3/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 961, in get_nearest_neighbors
    await to_thread.run_sync(
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 940, in process_query
    query = QueryEmbedding.model_validate(orjson.loads(raw_body))
orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)
[32mINFO[0m:     [03-05-2024 15:04:03] ::1:60323 - "POST /api/v1/collections/c5b7828b-bb37-4826-9b5a-d99f13f9939b/query HTTP/1.1" 500
[32mINFO[0m:     [03-05-2024 15:06:04] ::1:60868 - "GET /api/v1/collections/c5b7828b-bb37-4826-9b5a-d99f13f9939b/count HTTP/1.1" 200
[31mERROR[0m:    [03-05-2024 15:06:19] Input is a zero-length, empty document: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/Users/codietamida/anaconda3/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 852, in get
    await to_thread.run_sync(
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "/Users/codietamida/Desktop/481_project/AI_embedding/venv/lib/python3.10/site-packages/chromadb/server/fastapi/__init__.py", line 831, in process_get
    get = GetEmbedding.model_validate(orjson.loads(raw_body))
orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)
[32mINFO[0m:     [03-05-2024 15:06:19] ::1:60931 - "POST /api/v1/collections/c5b7828b-bb37-4826-9b5a-d99f13f9939b/get HTTP/1.1" 500
[32mINFO[0m:     [03-05-2024 15:06:33] ::1:60986 - "GET /api/v1/count_collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:07:01] ::1:61104 - "GET /api/v1 HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:22:12] ::1:65053 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:22:12] ::1:65053 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:22:15] ::1:65070 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:22:15] ::1:65070 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:22:16] ::1:65078 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:22:16] ::1:65078 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:23:40] ::1:65437 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:23:40] ::1:65437 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:23:41] ::1:65447 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:23:41] ::1:65447 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:25:46] ::1:49636 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:25:46] ::1:49636 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:25:48] ::1:49644 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:25:48] ::1:49644 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:26:44] ::1:49890 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:26:44] ::1:49890 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:26:45] ::1:49904 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [03-05-2024 15:26:45] ::1:49904 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:56:15] Set chroma_server_nofile to 65535
[32mINFO[0m:     [06-05-2024 01:56:15] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [06-05-2024 01:56:15] Starting component System
[36mDEBUG[0m:    [06-05-2024 01:56:15] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [06-05-2024 01:56:15] Starting component SqliteDB
[36mDEBUG[0m:    [06-05-2024 01:56:15] Starting component QuotaEnforcer
[36mDEBUG[0m:    [06-05-2024 01:56:15] Starting component Posthog
[36mDEBUG[0m:    [06-05-2024 01:56:15] Starting component LocalSegmentManager
[36mDEBUG[0m:    [06-05-2024 01:56:15] Starting component SegmentAPI
[32mINFO[0m:     [06-05-2024 01:56:15] Started server process [[36m1742[0m]
[32mINFO[0m:     [06-05-2024 01:56:15] Waiting for application startup.
[32mINFO[0m:     [06-05-2024 01:56:15] Application startup complete.
[32mINFO[0m:     [06-05-2024 01:56:15] Uvicorn running on [1mhttp://localhost:8000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [06-05-2024 01:56:23] ::1:49675 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:56:23] ::1:49675 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:56:25] ::1:49680 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:56:25] ::1:49680 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:56:27] ::1:49685 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:56:27] ::1:49685 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:56:49] ::1:49698 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:56:49] ::1:49698 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:56:50] ::1:49704 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:56:50] ::1:49704 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:58:09] ::1:49814 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:58:09] ::1:49814 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:58:11] ::1:49819 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:58:11] ::1:49819 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:58:42] ::1:49839 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:58:42] ::1:49839 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:58:44] ::1:49846 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 01:58:44] ::1:49846 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:06:00] ::1:50021 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:06:00] ::1:50021 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:06:02] ::1:50025 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:06:02] ::1:50025 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:08:36] ::1:50058 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:08:36] ::1:50058 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:08:37] ::1:50063 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:08:37] ::1:50063 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:26:28] ::1:52513 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:26:28] ::1:52513 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:26:42] ::1:52573 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:26:42] ::1:52573 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:26:43] ::1:52587 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:26:43] ::1:52587 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:30:18] ::1:53495 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:30:18] ::1:53495 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:30:20] ::1:53508 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:30:20] ::1:53508 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:58:24] ::1:60649 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:58:24] ::1:60649 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:58:25] ::1:60659 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [06-05-2024 02:58:25] ::1:60659 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
